IA-1655: update readme and add diagram
USSBA/terraform-aws-cstate-healthchecker pull request #6
Opened 2020-11-10 17:11 UTC by jsmigovsky

2020-11-11 14:07 UTC, elijahmuha requested changes

2020-11-11 14:07 UTC, elijahmuha commented on README.md
> +* Configuratble ability to ignore short downtime if desired
I think I would rewrite this as something like:
`Ability to ignore downtime for a desired duration, e.g. ignore downtime of 5 min or less`

2020-11-12 14:22 UTC, bushong1 approved these changes

2020-11-12 14:25 UTC, bushong1 approved these changes

2020-11-12 14:26 UTC, merged